name: 'Setup Mojo'
description: 'Set up Mojo language'
inputs:
  version:
    description: 'The Mojo version to install'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - run: setup-mojo.sh ${{ inputs.version }}
      shell: bash
