name: Test Setup Mojo Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Mojo
      uses: ./
      with:
        version: '2024.7.1805'
    - name: Verify Mojo installation
      run: |
        mojo --version
        echo "Modular Home: $MODULAR_HOME"
